package view.gui;

public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GoUser = new javax.swing.JButton();
        GoSala = new javax.swing.JButton();
        GoPelicula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GoUser.setText("USER");
        GoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoUserActionPerformed(evt);
            }
        });

        GoSala.setText("SALA");
        GoSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoSalaActionPerformed(evt);
            }
        });

        GoPelicula.setText("PELI");
        GoPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoPeliculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(GoUser)
                .addGap(97, 97, 97)
                .addComponent(GoSala)
                .addGap(102, 102, 102)
                .addComponent(GoPelicula)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GoUser)
                    .addComponent(GoSala)
                    .addComponent(GoPelicula))
                .addContainerGap(202, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoPeliculaActionPerformed
        CrearPeli CrearPeli = new CrearPeli(); // Crear una instancia del formulario Home
        CrearPeli.setVisible(true);  // Mostrar Home
        this.dispose();         // Cerrar el formulario actual
    }//GEN-LAST:event_GoPeliculaActionPerformed

    private void GoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoUserActionPerformed
        CrearUser CrearUser = new CrearUser(); // Crear una instancia del formulario Home
        CrearUser.setVisible(true);  // Mostrar Home
        this.dispose();         // Cerrar el formulario actual
    }//GEN-LAST:event_GoUserActionPerformed

    private void GoSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoSalaActionPerformed
        CrearSala CrearSala = new CrearSala(); // Crear una instancia del formulario Home
        CrearSala.setVisible(true);  // Mostrar Home
        this.dispose();         // Cerrar el formulario actual
    }//GEN-LAST:event_GoSalaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoPelicula;
    private javax.swing.JButton GoSala;
    private javax.swing.JButton GoUser;
    // End of variables declaration//GEN-END:variables
}
